# Generated by Django 3.0 on 2022-08-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('gallery', 'Gallery'), ('news', 'Paid')], default='gallery', max_length=255, verbose_name='Type')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='main.Production')),
            ],
        ),
    ]
