# Generated by Django 3.0 on 2022-08-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=80, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(db_index=True, max_length=80, null=True, verbose_name='Name'),
        ),
    ]
