# Generated by Django 3.0 on 2022-08-19 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionimage',
            name='type',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('news', 'News')], default='gallery', max_length=255, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='TeamMemberSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('type', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'Youtube'), ('instagram', 'Instagram'), ('website', 'Website')], max_length=255, verbose_name='Type')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='main.TeamMember')),
            ],
        ),
    ]
