# Generated by Django 3.0 on 2022-08-19 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220819_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembersocialmedia',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_media_links', to='main.TeamMember'),
        ),
    ]
