# Generated by Django 3.0 on 2022-08-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productionschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionschedule',
            name='production',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='main.Production'),
            preserve_default=False,
        ),
    ]
