# Generated by Django 3.0 on 2022-08-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productionevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionevent',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='production',
            name='partners_image',
            field=models.ImageField(blank=True, null=True, upload_to='partners', verbose_name='Partners Photo'),
        ),
        migrations.AlterField(
            model_name='production',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Embed Youtube Link'),
        ),
        migrations.AlterField(
            model_name='production',
            name='synopsis',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='production',
            name='synopsis_ar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='production',
            name='synopsis_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='main.Category', verbose_name='Category'),
        ),
    ]
