# Generated by Django 3.0 on 2022-08-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220813_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='main.Category', verbose_name='Sub Category'),
            preserve_default=False,
        ),
    ]
