# Generated by Django 3.0 on 2022-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('synopsis', models.TextField(max_length=5000, verbose_name='Synopsis')),
                ('link', models.URLField(verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
