# Generated by Django 3.0 on 2022-08-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_productionschedule_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionschedule',
            name='place',
            field=models.CharField(max_length=150, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='place_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='place_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='title_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='productionschedule',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Time'),
        ),
    ]
