# Generated by Django 3.0 on 2022-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='synopsis_ar',
            field=models.TextField(max_length=5000, null=True, verbose_name='Synopsis'),
        ),
        migrations.AddField(
            model_name='production',
            name='synopsis_en',
            field=models.TextField(max_length=5000, null=True, verbose_name='Synopsis'),
        ),
        migrations.AddField(
            model_name='production',
            name='title_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='production',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Title'),
        ),
    ]
