# Generated by Django 3.0 on 2022-08-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220819_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionprogram',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='main.Production'),
        ),
    ]
