# Generated by Django 3.0 on 2022-08-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220819_1830'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductionProgram',
            new_name='ProductionEvent',
        ),
    ]
