# Generated by Django 3.0 on 2022-08-13 12:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
