# Generated by Django 3.0 on 2022-08-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220813_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='productions', to='main.SubCategory', verbose_name='Sub Category'),
            preserve_default=False,
        ),
    ]
