# Generated by Django 3.0 on 2022-08-13 16:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_production_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='title', unique_with=['title', 'created_at']),
            preserve_default=False,
        ),
    ]
