# Generated by Django 3.0 on 2022-08-13 16:47

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_production_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('job_title', models.CharField(max_length=150, verbose_name='Job Title')),
                ('image', models.ImageField(upload_to='covers', verbose_name='Cover Photo')),
                ('bio', models.TextField(blank=True, max_length=5000, verbose_name='Full Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['name', 'created_at'])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
