# Generated by Django 3.0 on 2022-08-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='bio_ar',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='job_title_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='job_title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Full Name'),
        ),
    ]
