# Generated by Django 3.0 on 2022-08-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220813_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='publish_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Publish At'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio_ar',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='covers', verbose_name='Personal Photo'),
        ),
    ]
