# Generated by Django 3.0 on 2022-08-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20220813_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='publish_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Publish At'),
        ),
    ]
