# Generated by Django 3.0 on 2022-08-13 21:19

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220813_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('content', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['title', 'created_at'])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
