# Generated by Django 3.0 on 2022-08-13 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_headlines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeadLines',
            new_name='HeadLine',
        ),
    ]
