# Generated by Django 4.1 on 2022-08-13 22:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_headline_content_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
