# Generated by Django 3.0 on 2022-08-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_headline_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated At')),
                ('publish_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Publish At')),
                ('pdf', models.FileField(upload_to='annual_reports', verbose_name='PDF')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
