# Generated by Django 3.0 on 2022-08-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220814_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
