# Generated by Django 3.0 on 2022-08-14 23:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_production_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='synopsis',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='production',
            name='synopsis_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Synopsis'),
        ),
        migrations.AlterField(
            model_name='production',
            name='synopsis_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Synopsis'),
        ),
    ]
